version: '3'
services:
  web:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
  #   links:
  #     - mongodb
  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db